# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean White"
license = "Apache"
licenselink = "https://github.com/blowizer/hugo-theme-cleanwhite/blob/master/LICENSE"
description = "A clean, elegant blog theme for hugo"
homepage = "https://github.com/blwizer/hugo-theme-cleanwhite"
tags = ["minimal", "responsive", "blog", "light", "clean", "search"]
features = [
  "disqus",
  "site search",
  "responsive",
  "baidu analytics",
  "side bar",
]
min_version = 0.10

[author]
name = "blwizer"
homepage = "https://github.com/blowizer"

# If porting an existing theme
[original]
name = "huxblog"
homepage = "https://github.com/Huxpro/huxpro.github.io"
